from application.services.estudiante_service import EstudianteService


def seed_estudiantes(service: EstudianteService) -> None:
    """Carga 60 estudiantes de prueba en el repositorio en memoria."""

    estudiantes = [
        {"nombre": "Ana", "apellido": "Pérez", "email": "estudiante01@example.com"},
        {"nombre": "Luis", "apellido": "Muñoz", "email": "estudiante02@example.com"},
        {"nombre": "Camila", "apellido": "Silva", "email": "estudiante03@example.com"},
        {"nombre": "Diego", "apellido": "Morales", "email": "estudiante04@example.com"},
        {"nombre": "Sofía", "apellido": "Araya", "email": "estudiante05@example.com"},
        {"nombre": "Matías", "apellido": "Ramírez", "email": "estudiante06@example.com"},
        {"nombre": "Valentina", "apellido": "Navarro", "email": "estudiante07@example.com"},
        {"nombre": "Benjamín", "apellido": "González", "email": "estudiante08@example.com"},
        {"nombre": "Francisca", "apellido": "Soto", "email": "estudiante09@example.com"},
        {"nombre": "Tomás", "apellido": "Martínez", "email": "estudiante10@example.com"},
        {"nombre": "Isidora", "apellido": "Torres", "email": "estudiante11@example.com"},
        {"nombre": "Vicente", "apellido": "Castillo", "email": "estudiante12@example.com"},
        {"nombre": "Catalina", "apellido": "Reyes", "email": "estudiante13@example.com"},
        {"nombre": "Nicolás", "apellido": "Molina", "email": "estudiante14@example.com"},
        {"nombre": "Fernanda", "apellido": "Rojas", "email": "estudiante15@example.com"},
        {"nombre": "Sebastián", "apellido": "Contreras", "email": "estudiante16@example.com"},
        {"nombre": "Josefa", "apellido": "Sepúlveda", "email": "estudiante17@example.com"},
        {"nombre": "Gabriel", "apellido": "Flores", "email": "estudiante18@example.com"},
        {"nombre": "Martina", "apellido": "Vargas", "email": "estudiante19@example.com"},
        {"nombre": "Joaquín", "apellido": "Herrera", "email": "estudiante20@example.com"},
        {"nombre": "Ana", "apellido": "Pérez", "email": "estudiante21@example.com"},
        {"nombre": "Luis", "apellido": "Muñoz", "email": "estudiante22@example.com"},
        {"nombre": "Camila", "apellido": "Silva", "email": "estudiante23@example.com"},
        {"nombre": "Diego", "apellido": "Morales", "email": "estudiante24@example.com"},
        {"nombre": "Sofía", "apellido": "Araya", "email": "estudiante25@example.com"},
        {"nombre": "Matías", "apellido": "Ramírez", "email": "estudiante26@example.com"},
        {"nombre": "Valentina", "apellido": "Navarro", "email": "estudiante27@example.com"},
        {"nombre": "Benjamín", "apellido": "González", "email": "estudiante28@example.com"},
        {"nombre": "Francisca", "apellido": "Soto", "email": "estudiante29@example.com"},
        {"nombre": "Tomás", "apellido": "Martínez", "email": "estudiante30@example.com"},
        {"nombre": "Isidora", "apellido": "Torres", "email": "estudiante31@example.com"},
        {"nombre": "Vicente", "apellido": "Castillo", "email": "estudiante32@example.com"},
        {"nombre": "Catalina", "apellido": "Reyes", "email": "estudiante33@example.com"},
        {"nombre": "Nicolás", "apellido": "Molina", "email": "estudiante34@example.com"},
        {"nombre": "Fernanda", "apellido": "Rojas", "email": "estudiante35@example.com"},
        {"nombre": "Sebastián", "apellido": "Contreras", "email": "estudiante36@example.com"},
        {"nombre": "Josefa", "apellido": "Sepúlveda", "email": "estudiante37@example.com"},
        {"nombre": "Gabriel", "apellido": "Flores", "email": "estudiante38@example.com"},
        {"nombre": "Martina", "apellido": "Vargas", "email": "estudiante39@example.com"},
        {"nombre": "Joaquín", "apellido": "Herrera", "email": "estudiante40@example.com"},
        {"nombre": "Ana", "apellido": "Pérez", "email": "estudiante41@example.com"},
        {"nombre": "Luis", "apellido": "Muñoz", "email": "estudiante42@example.com"},
        {"nombre": "Camila", "apellido": "Silva", "email": "estudiante43@example.com"},
        {"nombre": "Diego", "apellido": "Morales", "email": "estudiante44@example.com"},
        {"nombre": "Sofía", "apellido": "Araya", "email": "estudiante45@example.com"},
        {"nombre": "Matías", "apellido": "Ramírez", "email": "estudiante46@example.com"},
        {"nombre": "Valentina", "apellido": "Navarro", "email": "estudiante47@example.com"},
        {"nombre": "Benjamín", "apellido": "González", "email": "estudiante48@example.com"},
        {"nombre": "Francisca", "apellido": "Soto", "email": "estudiante49@example.com"},
        {"nombre": "Tomás", "apellido": "Martínez", "email": "estudiante50@example.com"},
        {"nombre": "Isidora", "apellido": "Torres", "email": "estudiante51@example.com"},
        {"nombre": "Vicente", "apellido": "Castillo", "email": "estudiante52@example.com"},
        {"nombre": "Catalina", "apellido": "Reyes", "email": "estudiante53@example.com"},
        {"nombre": "Nicolás", "apellido": "Molina", "email": "estudiante54@example.com"},
        {"nombre": "Fernanda", "apellido": "Rojas", "email": "estudiante55@example.com"},
        {"nombre": "Sebastián", "apellido": "Contreras", "email": "estudiante56@example.com"},
        {"nombre": "Josefa", "apellido": "Sepúlveda", "email": "estudiante57@example.com"},
        {"nombre": "Gabriel", "apellido": "Flores", "email": "estudiante58@example.com"},
        {"nombre": "Martina", "apellido": "Vargas", "email": "estudiante59@example.com"},
        {"nombre": "Joaquín", "apellido": "Herrera", "email": "estudiante60@example.com"},
    ]

    for datos in estudiantes:
        service.crear(
            nombre=datos["nombre"],
            apellido=datos["apellido"],
            email=datos["email"],
        )
